### ISSUE TITLE
Issues with next version of ggplot2

### ISSUE THREAD

**Issue by thomasp85** [Ryo-N7/tvthemes#20]
Hi

We preparing the next release of ggplot2 and our reverse dependency checks show that your package is failing with the new version. Looking into it we see that the issues are due to our switch to using the `linewidth` aesthetic for stroke width instead of `size`. Please see https://www.tidyverse.org/blog/2022/08/ggplot2-3-4-0-size-to-linewidth/ for more info on this.

You can install the release candidate of ggplot2 using `devtools::install_github('tidyverse/ggplot2@v3.4.0-rc')` to test this out.

We plan to submit ggplot2 by the end of October and hope you can have a fix ready before then

Kind regards
Thomas

**Comment by Ryo-N7** [comment]
understood, thank you for notifying me

yep, i see the problems:
![linewidth-size](https://user-images.githubusercontent.com/19657164/194991822-61956b36-deb7-41a8-8991-a92b5f965970.PNG)

allrighty, will get a fix on CRAN soon

**Comment by Ryo-N7** [comment]
Prepare for release:

- [x] Check [current CRAN check results](https://cran.rstudio.org/web/checks/check_results_tvthemes.html)
- [x] Update `NEWS.md`
- [x] `devtools::build_readme()`
- [x] `urlchecker::url_check()`
- [x] `devtools::check(remote = TRUE, manual = TRUE)`
- [x] `devtools::check_win_devel()`
- [x] `rhub::check_for_cran()`
- [x] `rhub::check(platform = 'ubuntu-rchk')`
- [x] `rhub::check_with_sanitizers()`
- [x] `revdepcheck::cloud_check()`
- [x] Update `cran-comments.md`

Submit to CRAN >>> (**when ggplot2 is ready, end of October**):

- [x] `usethis::use_version('patch')`
- [ ] `devtools::submit_cran()`
- [ ] Approve email

Wait for CRAN...

Accepted 🎉

- [ ] usethis::use_github_release()
- [ ] usethis::use_dev_version()
